name: Deploy Next.js to GitHub Pages (Docker)

on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build with Docker
        run: |
          docker build -t nextjs-build .
          docker create --name extract nextjs-build
          docker cp extract:/app/out ./out
          docker rm extract

      - uses: actions/upload-pages-artifact@v3
        with:
          path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
